security:
    # Encoders pour hacher les mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Définition des utilisateurs (en mémoire)
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$13$8LU4xpJ57/PDvdHrxUNWeOn6rGfzcRrRbWpPgviK.xGYnDsoQXxNq' # Mot de passe "StudiECF!" encodé avec bcrypt
                        roles: ['ROLE_ADMIN']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: in_memory
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
