security:
    enable_authenticator_manager: true 
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$13$8LU4xpJ57/PDvdHrxUNWeOn6rGfzcRrRbWpPgviK.xGYnDsoQXxNq' # Mot de passe : StudiECF!
                        roles: ['ROLE_ADMIN']

    firewalls:
        main:
            lazy: true
            provider: in_memory
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
